### ISSUE TITLE
How can i Added my own library to the list?

### ISSUE THREAD

**Issue by colesnicov** [njh/arduino-libraries#10]
Good day to you. Please, I have written a smaller library with name [IRQSwitch](https://github.com/colesnicov/IRQSwitch) to make it easier to work with the buttons. The library is in development, I would still like to develop it and so I need feedback from the user. I'd like to know about her so that people use it and write me Issues and send me Pull Requests if you understand how to think. As please, I can add my library to this list at http://arduinolibraries.info.
I apologize for my English, Google translator, and I just add the original in Czech.

Thank you.

**Comment by njh** [comment]
The libraries on the website are the same as the libraries listed in the [Arduino Library Manager](https://www.arduino.cc/en/Guide/Libraries).

There are details on how to add a library to the Library Manager here:
[How can I add my library to Library Manager?](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager)
