### ISSUE TITLE
Library list is not up to date

### ISSUE THREAD

**Issue by Spirik** [njh/arduino-libraries#13]
Site hasn't been updated since 04/28/2020 (at least that's what it says in the footer). Are there any plans currently to restore it to working order? I was usually referring to it to see, if release of my library were successfully published and available to users through Library Manager. Thx!

**Comment by njh** [comment]
Hm! The site build does occasionally fail when people delete Github repos.

However I recently changed mail servers and stopped getting the error reports.

Should all be fixed now. Thanks for letting me know 👍

**Comment by JAndrassy** [comment]
please check the update process. "Most Recent" is from May 2 and is labeled as "today"
at least "Arduino_Braccio_plusplus" has a new version in Library Manager in IDE since then.

**Comment by njh** [comment]
I have raised a new issue: #23

The currently problem is not related to this one (#13).
