### ISSUE TITLE
Website not updating

### ISSUE THREAD

**Issue by njh** [njh/arduino-libraries#23]
The https://www.arduinolibraries.info/ is not currently updating because the server that builds the website is currently offline.

The website is built on a Jenkins server and the website itself is hosted on a different machine.

**Comment by roboticboyer** [comment]
The RSS link is not updated
[https://www.arduinolibraries.info/feed.xml](https://www.arduinolibraries.info/feed.xml)

**Comment by njh** [comment]
I fixed this on the 27th June: https://twitter.com/njh/status/1541535198260649984

Sorry, forgot to update this issue.
