### ISSUE TITLE
Simblee board lib still available; and, reinstalling phone app

### ISSUE THREAD

**Issue by papaJupe** [njh/arduino-libraries#29]
I don't have skill needed to add this info myself to this site, and link to it should be on NJH's arduinolibraries.info site as well. I see posts online that the few still trying to use the Simblee BLE boards, programmed via the Arduino IDE, have a high level of frustration due to disappearance of support libraries. A Mr. Thatcher has kindly kept these available, so you might do these intrepid few a favor by including this on your web page for  archived Simblee libs:
https://github.com/mthatcher/Simblee-Build-Archive

I've also found a way some might be able to restore the (now missing from app stores) Simblee app for Android and iOS, tho that info doesn't seem to belong on your library site (worked for me on iPhone 6). LMK if you know somewhere it could be usefully posted.

**Comment by njh** [comment]
Arduino libraries on the [arduinolibraries.info](https://www.arduinolibraries.info/) website are just taken from the main Arduino Library Manager, built-into the IDE.

There is information about how to add a library to the library manager here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager
