### ISSUE TITLE
How often does "Most Starred" section update?

### ISSUE THREAD

**Issue by vshymanskyy** [njh/arduino-libraries#3]
Our library should get to top 10 now, but it looks like the section is not updated for a long lime...
Thx.

**Comment by z3t0** [comment]
I'm not sure if it's automated. From what I can tell the project maintainer rebuilds it and then uploads the static site.

**Comment by njh** [comment]
I have been having trouble that, for an unknown reason, I have not been 'Watching' all of my own repos, so I did not see this issue.

The "Most Starred" section indeed didn't used to get updated but it has been updating nightly now for a while.
