### ISSUE TITLE
An abandoned library with a bug and some issues. 

### ISSUE THREAD

**Issue by MiyukiDark** [njh/arduino-libraries#31]
Hello, 
I was trying to use the DMD32 library for the ESP32 platform. 
It did not work against newer versions of Arduino libs, 2.0.3 and up. 
It can be easily fixed. But it looks to be abandoned by the author. 
Should it be replaced by a patched fork if the author won't respond?

**Comment by njh** [comment]
This GitHub project is just a website that lists the available libraries from the official Arduino registry.

Arduino libraries are managed here: https://github.com/arduino/library-registry

I suspect that the answer is that if it is abandoned, that a fork will have to be created with a new name.
