### ISSUE TITLE
Seems to be stuck, RSS feed and front page claim latest updated adafruit library from 1st September

### ISSUE THREAD

**Issue by tyeth** [njh/arduino-libraries#36]
Seems to be stuck, RSS feed and front page claim latest updated adafruit library from "Yesterday" and when clicked that is listed as 1st September.

Thanks for this great service by the way ❤️

**Comment by Spirik** [comment]
Yes, indeed, timestamp in footer claims that content was last updated September 3rd.

<img width="599" alt="image" src="https://github.com/njh/arduino-libraries/assets/1061406/23d1b849-05ac-4814-a6bc-3bc9bd6f3a03">

**Comment by njh** [comment]
Really sorry about this. The website is rebuilt periodically by a computer under my stairs(!).

However my house doesn't have power/internet at the moment.
Will try and get something sorted out.

**Comment by tyeth** [comment]
> Really sorry about this. The website is rebuilt periodically by a computer under my stairs(!).


Lol, as all good things on the internet should be 🥰

Good luck with sorting the power and networking 🤞

**Comment by fabianoriccardi** [comment]
Any news on this topic? The website is still stuck at that date...

**Comment by fabianoriccardi** [comment]
Hi @njh, are you well? If you need help to host the website let us know

**Comment by njh** [comment]
Sorry, we were without sockets in our house for much longer than expected.
I have just been reconnecting everything and server that builds website is back up and running now.

Site should update in the coming hours...

**Comment by tyeth** [comment]
Looks good, closing this for now. Thanks @njh for your hard work and continuing upkeep! ⭐

**Comment by marcelstoer** [comment]
@njh do you update the site library by library or all at once? The startpage shows libs updated today but one of our libs still doesn't list the latest version: https://www.arduinolibraries.info/libraries/esp8266-and-esp32-oled-driver-for-ssd1306-displays (contrary to the [Arduino site](https://www.arduino.cc/reference/en/libraries/esp8266-and-esp32-oled-driver-for-ssd1306-displays/)).

**Comment by tyeth** [comment]
Yeah been no updates today since very early in the AM about 8hrs before @njh's comment, probably just needs a kick

**Comment by njh** [comment]
Sorry, the site is failing to build due to bad data.
I have been working through fixing things, hopefully it will all be resolved today.

**Comment by njh** [comment]
The script keeps getting stuck, while looking up the commit ids for each of the library versions.
I might have to make some changes to the number of versions that are published on the library pages.

**Comment by njh** [comment]
I have got my home development computer up and running now.

I have been running a site build locally to try and see what is going wrong.
It looks like I am hitting the GitHub API rate limit.

**Comment by tyeth** [comment]
Wow, I suppose that makes sense, was it 5k per hour or something if you sign in / use a token? You do analyse the arduino world on our behalf, so that must be thousands of hits. Good luck with the fix!

**Comment by marcelstoer** [comment]
> It looks like I am hitting the GitHub API rate limit.

Did you confirm by checking [the rate limit response headers](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#checking-the-status-of-your-rate-limit)?

> was it 5k per hour or something if you sign in / use a token?

Yes, [5k it is](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-authenticated-users). Not bad but 1.3 requests/second isn't all that much either. (remedy: open a number of dummy GH accounts and use their tokens in round-robin)

**Comment by tyeth** [comment]
You might be able to be sponsored for contributing to the open source community (maybe an MS + Github application rather than GH direct), or alternatively we can chuck you the £21/month (£2 x 10 caring users) for an enterprise team plan of one user for a better rate limit of 15,000 (but would also need to be an App rather than token approach).

> (remedy: open a number of dummy GH accounts and use their tokens in round-robin)

Or, we won't tell if you won't ;)

**Comment by marcelstoer** [comment]
Out of curiosity I added `sleep(1/1.3)` at https://github.com/njh/arduino-libraries/blob/main/lib/github.rb#L23 to see how far this would get me - or how long the build will run. No idea how many requests a full build will issue.

Unfortunately, it failed rather early as user 'vase7u' doesn't exist anymore and https://github.com/njh/arduino-libraries/blob/7015c98859e55c50b0362279a111b48f93330a74/bin/fetch-github-users.rb#L28-L44 fails in this case.

**Comment by njh** [comment]
I have just noticed that the `github_commits.json` gets over 500MB. That is way bigger than I ever intended it to get.
It would be a lot more efficient if it used a database instead (SQLite even) but that is a significant change.
However the constant dumping of the commit data to the JSON file might also be slowing things down enough that it didn't used to hit rate limits.

I have [committed a change](https://github.com/njh/arduino-libraries/commit/725af21d0bfacd5713dd624de9bae64f4c36299e) to limit the number of versions to 10. That might allow it to get through a complete build for now:

**Comment by njh** [comment]
Finally got there today! Site has updated at last.

The original approach does not scale to 6362 libraries.
It has to load far too much data from GitHub:
* `github_commits.json` - 611Mb
* `github_repos.json` - 44Mb
* `github_users.json` - 3.4Mb

I am going to close this ticket but some improvements changes are required if this site is going to continue:
* Store data in a database, instead of JSON files
* See if more data (particularly commits) can be provided by Arduino in [library_index.json](https://downloads.arduino.cc/libraries/library_index.json)
* Refresh data more intelligently
* Refresh site less frequently
