### ISSUE TITLE
Duplicate libraries are not handled correctly

### ISSUE THREAD

**Issue by cujomalainey** [njh/arduino-libraries#6]
The arduino package manager allowed some libraries to update their names while they were hardening changes with their package tracker. This as a result has broken some of the systems package tracking.

See https://github.com/arduino/Arduino/issues/7127 for list of libraries potentially affected.

As a result my library shows up under 2 locations ([here](https://www.arduinolibraries.info/libraries/ant-arduino) and [here](https://www.arduinolibraries.info/libraries/ant-arduino-library)) and the old url does not show my latest 1.0.2 release

I would recommend the https://www.arduinolibraries.info/libraries/ant-arduino-library (the old location) to be purged.

Thanks again for your tracker.

**Comment by njh** [comment]
Hm! 

It looks like one of the pages hasn't been updated since the 21st January.
So it looks like there is a bug that is not deleting old pages that haven't been updated.

**Comment by njh** [comment]
I think I have have fixed this by running `rake clean` every night.
