### ISSUE TITLE
By License

### ISSUE THREAD

**Issue by scls19fr** [njh/arduino-libraries#7]
Hello,

adding a "By License" list to https://www.arduinolibraries.info/ could be an interesting feature.

Kind regards

Related issue #5

**Comment by njh** [comment]
Code added in c9011a6286fab0b5c75342197a68fa2a4a8f6625

I also need to validate SPDX license identifiers at some point - I am currently seeing both 'BSD 3 clause ' and 'BSD 3 Clause'.

Currently waiting for website to update...

**Comment by njh** [comment]
SPDX licence validation added in cbfbe35df7704d07838e37ec657fbe0fe2c027ff.

New 'By License' section working on website.

**Comment by scls19fr** [comment]
Numbers are quite odd... only 10 unlicensed packages ?
Moreover sum of these number should be total number of packages, isn't it?
Oh sorry I noticed Unlicensed is name of a license.
Maybe number of packages with an "unknown" license be displayed
